# Generated by Django 4.2.5 on 2023-09-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QrCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_created", models.DateField()),
                ("name", models.CharField(max_length=50)),
                ("token", models.CharField(max_length=300)),
                ("date_finish", models.DateField()),
            ],
        ),
    ]
