# Generated by Django 4.2.5 on 2023-09-17 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qr_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qrcode",
            old_name="data_created",
            new_name="date_created",
        ),
    ]
