# Generated by Django 4.2.5 on 2023-09-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr_manager", "0003_customvariable"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="senha",
            field=models.CharField(default="000000#", max_length=7),
            preserve_default=False,
        ),
    ]
